security:
    firewalls:
        customer:
            pattern: /%uvdesk_support_center_routing_prefix%
            provider: user_provider
            anonymous: ~
            form_login:
                use_referer: true
                login_path: helpdesk_customer_login
                check_path: helpdesk_customer_login
                default_target_path: helpdesk_customer_ticket_collection
                always_use_default_target_path: true
            logout:
                path: helpdesk_customer_logout
                target: helpdesk_customer_login

    access_control:
        - { path: /%uvdesk_support_center_routing_prefix%/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /%uvdesk_support_center_routing_prefix%/create-ticket, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /%uvdesk_support_center_routing_prefix%/forgot-password, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /%uvdesk_support_center_routing_prefix%/update-credentials, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: /%uvdesk_support_center_routing_prefix%/, roles: ROLE_CUSTOMER }
